
spring:
  datasource:
    url: jdbc:tc:postgresql:latest:///testdb
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  mail:
    host: localhost
    port: 1025
    username:
    password:

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: false
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000